---
- name: Create EC2 instance first cluster
  ec2:
    instance_type: "{{ instace_type }}"
    image: "{{ image }}"
    group: "{{ security_group }}"
    keypair: "{{ keypair }}"
    region: "{{ region }}"
    monitoring: no
    wait: true
    count: 1
    volumes:
      - device_name: /dev/sda1 #Chainge root disk size
        volume_type: gp2
        volume_size: 15
        delete_on_termination: true
    instance_tags:
      Name: first-db-cluster
      Type: cluster
  register: ec2

- name: Print information about EC2 instance first cluster
  debug: 
    var: ec2.instances
  
- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
  lineinfile:
    dest: "./hosts"
    regexp: "{{ item.public_ip }}"
    insertafter: '\[db_cluster\]'
    line: "{{ item.tags.Name }}  ansible_host={{ item.public_ip }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem ansible_ssh_user=ubuntu server_type={{ item.tags.Type }}"
    state: present
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"