---
- name: Create EC2 instance
  ec2:
      instance_type: "{{ instace_type }}"
      image: "{{ image }}"
      group: "{{ security_group }}"
      keypair: "{{ keypair }}"
      region: "{{ region }}"
      monitoring: no
      wait: true
      count: 1
      volumes:
        - device_name: /dev/sda1 #Chainge root disk size
          volume_type: gp2
          volume_size: 25
          delete_on_termination: true
      instance_tags:
        Name: magento2
        Type: webserver
  register: ec2

- name: Print information about EC2 instance
  debug: 
    var: ec2.instances

- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
  lineinfile:
    dest: "./hosts"
    regexp: "{{ item.public_ip}}"
    insertafter: "[web]"
    line: "{{ item.public_ip }} -- {{ item.tags.Name }}"
    state: present
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"