# tasks file for ec2
---
    - name: Get information about vpc and subnet
      ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ vpc_name }}_subnet"
      register: vpc_subnet_facts
   
    - name: Set up subnets id
      vars:
        json: "{{ vpc_subnet_facts }}"
        query: "subnets[0].id"
        subnets: "{{ json | json_query(query) }}"
      set_fact:
        subnets: "{{ subnets }}"

    - name: Create EC2 instances
      ec2:
        instance_type: "{{ instace_type }}"
        image: "{{ image }}"
        group: "{{ security_group }}"
        keypair: "{{ keypair }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnets }}"
        assign_public_ip: yes
        monitoring: no
        wait: true
        count: 1
        volumes:
          - device_name: /dev/sda1 #Chainge root disk size
            volume_type: gp2
            volume_size: 15
            delete_on_termination: true
        instance_tags:
            Name: test-server
            Type: test-server
            Env: test
      register: ec2
        
    - name: Print information about EC2 instance
      debug: 
        var: ec2.instances
          
    - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
      lineinfile:
        dest: "./hosts"
        regexp: "{{ item.public_ip }}"
        insertafter: '\[web\]'
        line: "{{ item.tags.Name }}  ansible_host={{ item.public_ip }} {{ ssh_key }}=~/.ssh/{{ keypair }}.pem {{ user }}=ubuntu server_type={{ item.tags.Type }}"
        state: present
      with_items: "{{ ec2.instances }}"
        
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"