---
- name: add mariadb key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xF1656F24C74CD1D8"

- name: add mariadb repo
  apt_repository:
    repo: "deb http://sfo1.mirrors.digitalocean.com/mariadb/repo/{{ mariadb_version }}/ubuntu bionic main"
    state: present

- name: install the latest version of mariadb
  apt:
    name: "{{ mariadb_packages }}"
    update_cache: yes
  register: mysql_install_packages
