---
# tasks file for mariadb
- name: Install mariadb
  include: install.yml

- name: Configure mariadb
  include: configure.yml
  
- import_tasks: secure_installation.yml
- import_tasks: databases.yml
- import_tasks: users.yml