---
- name: disable remote root login
  command: mysql -NBe "delete from mysql.user where user='root' and host not in ('localhost', '127.0.0.1', '::1')"
  changed_when: false

- name: get list of hosts for the root user
  command: mysql -NBe "select host from mysql.user where user='root' order by (host='localhost') asc"
  register: root_hosts
  changed_when: false
  check_mode: no
  when: mysql_install_packages | bool or mysql_root_password_force_update

- name: update root password for localhost
  command: mysql -NBe 'alter user "root"@"{{ item }}" identified by "{{ mysql_root_password }}";'
  with_items: "{{ root_hosts.stdout_lines|default([]) }}"
  when: mysql_install_packages | bool or mysql_root_password_force_update

- name: copy .my.cnf file with root password creds
  template:
    src: root-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  when: mysql_install_packages | bool or mysql_root_password_force_update

- name: get list of hosts for anon user
  command: mysql -NBe 'select host from mysql.user where user=""'
  register: anon_hosts
  changed_when: false
  check_mode: no

- name: remove anon users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ anon_hosts.stdout_lines|default([]) }}"

- name: remove test db
  mysql_db:
    name: test
    state: absent