---
- name: Deploy Wordpress
  hosts: wordpres
  remote_user: ubuntu
  become: yes
  gather_facts: False

  pre_tasks:
    - name: Update and install python
      raw: 'sudo apt-get install -y python '
  
  roles:
    - apache
    - php7.0
    - mysql
    - wordpress