---
- hosts: local
  gather_facts: False
  connection: local

  vars_files:
    - ./vaul/aws_cred.yml

  tasks:
    
    - name: Create security group for instance
      ec2_group:
        name: "{{ security_group }}"
        description: Wordpress group
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Create EC2 instance
      ec2:
        instance_type: "{{ instace_type }}"
        image: "{{ image }}"
        group: "{{ security_group }}"
        keypair: "{{ keypair }}"
        region: "{{ region }}"
        monitoring: no
        wait: true
        count: 1
        volumes:
          - device_name: /dev/sda1 #Chainge root disk size
            volume_type: gp2
            volume_size: 50
            delete_on_termination: true
      register: ec2


    - name: Print information about EC2 instance
      debug: 
        var: ec2.instances
    
    - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
      lineinfile:
        dest: "./hosts"
        regexp: "{{ item.public_ip }}"
        insertafter: '\[wordpres\]'
        line: "{{ item.public_ip }}"
        state: present
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

    - name: Add tag to Instance
      ec2_tag:
        resource: "{{ item.id }}"
        region: "{{ region }}"
        state: "present"
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Type: webserver
          Name: Wordpress
