---
- name: Update apt pakages
  apt: 
    update_cache: yes

- name: Install latest version of apache
  apt:
    name: apache2
    state: latest
  
- name: Enable apache2 
  service: 
    name: apache2
    state: started
    enabled: yes

