---
    - name: Create and run EC2 instances 
      hosts: localhost
      connection: local
      gather_facts: false

      roles:

        - role: vpc_groups
          tags: create vpc with security groups for ec2 